##### get news list

GET http://localhost:3000/news

#####

GET http://localhost:3000/news?lang=ru

#####

GET http://localhost:3000/news?lang=en

#####

GET http://localhost:3000/news?lang=tuw

##### get news item

GET http://localhost:3000/news/5

#####

GET http://localhost:3000/news/222?lang=ru

#####

GET http://localhost:3000/news/2?lang=en

#####

GET http://localhost:3000/news/3?lang=tuw

#####

POST http://localhost:3000/news?lang=en HTTP/1.1
content-type: application/json

{
    "title": "another tas 112 k",
    "date": "2017-02-07T21:00:00.000Z",
    "descr": "another 1 2description",
    "content": "r"
}

#####

PUT http://localhost:3000/news/16?lang=en HTTP/1.1
content-type: application/json

{
    "title": "updated",
    "date": "2017-02-07T21:00:00.000Z",
    "descr": "updated",
    "content": "updated"
}

#####

DELETE http://localhost:3000/news/16